function animate_planar_robot_with_floor(t, q, param)
%ANIMATE_PLANAR_ROBOT_WITH_FLOOR
% Animate the planar robot and horizontal floor.

    %% Playback settings

    playback_speed = 1.0;
    frame_rate = 30;

    animation_time = ...
        t(1):(playback_speed / frame_rate):t(end);

    animation_indices = interp1( ...
        t, ...
        1:length(t), ...
        animation_time, ...
        'nearest');

    animation_indices = ...
        unique(animation_indices);

    %% Position calculation

    number_of_samples = length(t);

    joint_position = ...
        zeros(number_of_samples, 2);

    ee_position = ...
        zeros(number_of_samples, 2);

    contact_force = ...
        zeros(number_of_samples, 2);

    for k = 1:number_of_samples

        q1 = q(k, 1);
        q2 = q(k, 2);

        joint_position(k, :) = [
            param.l1 * cos(q1), ...
            param.l1 * sin(q1)
        ];

        ee_position(k, :) = ...
            joint_position(k, :) ...
            + [
                param.l2 * cos(q2), ...
                param.l2 * sin(q2)
            ];

        [F_contact_k, ~] = ...
            surface_contact_force( ...
                q(k, :).', ...
                [0; 0], ...
                param);

        contact_force(k, :) = ...
            F_contact_k.';

    end

    %% Figure

    total_length = ...
        param.l1 + param.l2;

    axis_limit = ...
        1.1 * total_length;

    figure;

    hold on;
    grid on;
    axis equal;

    xlim([-axis_limit, axis_limit]);

    ylim([ ...
        min(-axis_limit, param.z_floor - 0.1), ...
        axis_limit]);

    xlabel('X [m]');
    ylabel('Z [m]');

    title('Planar robot with surface contact');

    %% Floor

    plot( ...
        [-axis_limit, axis_limit], ...
        [param.z_floor, param.z_floor], ...
        '-', ...
        'LineWidth', 3);

    %% Initial configuration

    k0 = animation_indices(1);

    p1 = joint_position(k0, :);
    p2 = ee_position(k0, :);

    link1_plot = plot( ...
        [0, p1(1)], ...
        [0, p1(2)], ...
        '-', ...
        'LineWidth', 4);

    link2_plot = plot( ...
        [p1(1), p2(1)], ...
        [p1(2), p2(2)], ...
        '-', ...
        'LineWidth', 4);

    plot(0, 0, ...
        'o', ...
        'MarkerSize', 9, ...
        'MarkerFaceColor', 'auto');

    joint_plot = plot( ...
        p1(1), p1(2), ...
        'o', ...
        'MarkerSize', 9, ...
        'MarkerFaceColor', 'auto');

    ee_plot = plot( ...
        p2(1), p2(2), ...
        'o', ...
        'MarkerSize', 9, ...
        'MarkerFaceColor', 'auto');

    trajectory_plot = plot( ...
        p2(1), p2(2), ...
        '--', ...
        'LineWidth', 1);

    force_plot = quiver( ...
        p2(1), ...
        p2(2), ...
        0, ...
        0, ...
        0, ...
        'LineWidth', 2);

    time_text = text( ...
        -0.95 * axis_limit, ...
         0.90 * axis_limit, ...
        sprintf('t = %.2f s', t(k0)));

    %% Animation

    force_scale = 0.01;

    for frame = 1:length(animation_indices)

        k = animation_indices(frame);

        p1 = joint_position(k, :);
        p2 = ee_position(k, :);

        set(link1_plot, ...
            'XData', [0, p1(1)], ...
            'YData', [0, p1(2)]);

        set(link2_plot, ...
            'XData', [p1(1), p2(1)], ...
            'YData', [p1(2), p2(2)]);

        set(joint_plot, ...
            'XData', p1(1), ...
            'YData', p1(2));

        set(ee_plot, ...
            'XData', p2(1), ...
            'YData', p2(2));

        set(trajectory_plot, ...
            'XData', ee_position(1:k, 1), ...
            'YData', ee_position(1:k, 2));

        set(force_plot, ...
            'XData', p2(1), ...
            'YData', p2(2), ...
            'UData', 0, ...
            'VData', ...
                force_scale ...
                * contact_force(k, 2));

        set(time_text, ...
            'String', ...
            sprintf( ...
                't = %.2f s, F_z = %.1f N', ...
                t(k), ...
                contact_force(k, 2)));

        drawnow;

    end

end