%% main_MCGFC_3d
clear;
close all;
clc;

%% Display settings

show_animation = true;
show_graphs = false;

%% Robot parameters

param = robot_parameters_all();

%% Initial state
%
% q1:
%   Absolute angle of link 1 in the radial-Z plane
%
% q2:
%   Absolute angle of link 2 in the radial-Z plane
%
% q3:
%   Root yaw angle about the world Z axis

q0 = [
    deg2rad(80);
    deg2rad(30);
    deg2rad(20)
];

dq0 = [
    0;
    0;
    0
];

x0 = [
    q0;
    dq0
];

%% Simulation settings

tspan = [0, 5.0];

options = odeset( ...
    'RelTol', 1e-7, ...
    'AbsTol', 1e-9, ...
    'MaxStep', 2e-4);

%% Run simulation
%
% Contact stiffness can make the differential equation
% numerically stiff.

[t, x] = ode15s( ...
    @(t, x) robot_model_3d( ...
        t, ...
        x, ...
        param), ...
    tspan, ...
    x0, ...
    options);

%% Evaluate simulation results

result = evaluate_simulation_3d( ...
    t, ...
    x, ...
    param);

%% Display numerical summary

display_simulation_summary_3d( ...
    result, ...
    param);

%% Animation

if show_animation

    animate_robot_3d( ...
        result, ...
        param);

end

%% Graphs

if show_graphs

    plot_simulation_results_3d( ...
        result, ...
        param);

end


function result = ...
    evaluate_simulation_3d(t, x, param)
%EVALUATE_SIMULATION_3D
% Recalculate and store model details at every simulation sample.

    %% State extraction

    q = x(:, 1:3);
    dq = x(:, 4:6);

    number_of_samples = length(t);

    %% State logs

    ddq = ...
        zeros(number_of_samples, 3);

    %% Dynamics logs

    M_log = ...
        zeros(3, 3, number_of_samples);

    c_log = ...
        zeros(number_of_samples, 3);

    G_log = ...
        zeros(number_of_samples, 3);

    command_torque_log = ...
        zeros(number_of_samples, 3);

    friction_torque_log = ...
        zeros(number_of_samples, 3);

    contact_torque_log = ...
        zeros(number_of_samples, 3);

    %% Kinematics logs

    joint_position = ...
        zeros(number_of_samples, 3);

    joint_velocity = ...
        zeros(number_of_samples, 3);

    ee_position = ...
        zeros(number_of_samples, 3);

    ee_velocity = ...
        zeros(number_of_samples, 3);

    %% Contact-force logs

    joint_contact_force = ...
        zeros(number_of_samples, 3);

    ee_contact_force = ...
        zeros(number_of_samples, 3);

    total_contact_force = ...
        zeros(number_of_samples, 3);

    %% Individual contact-torque logs

    joint_contact_torque = ...
        zeros(number_of_samples, 3);

    ee_contact_torque = ...
        zeros(number_of_samples, 3);

    %% Penetration logs

    joint_penetration = ...
        zeros(number_of_samples, 1);

    ee_penetration = ...
        zeros(number_of_samples, 1);

    %% Contact-state logs

    joint_contact_state = ...
        false(number_of_samples, 1);

    ee_contact_state = ...
        false(number_of_samples, 1);

    %% Contact component logs

    joint_contact_spring_force = ...
        zeros(number_of_samples, 1);

    joint_contact_damper_force = ...
        zeros(number_of_samples, 1);

    ee_contact_spring_force = ...
        zeros(number_of_samples, 1);

    ee_contact_damper_force = ...
        zeros(number_of_samples, 1);

    %% Friction component logs

    viscous_friction_torque = ...
        zeros(number_of_samples, 3);

    coulomb_friction_torque = ...
        zeros(number_of_samples, 3);

    %% Energy logs

    kinetic_energy = ...
        zeros(number_of_samples, 1);

    potential_energy = ...
        zeros(number_of_samples, 1);

    mechanical_energy = ...
        zeros(number_of_samples, 1);

    friction_power = ...
        zeros(number_of_samples, 1);

    %% Evaluate every sample

    for k = 1:number_of_samples

        x_k = ...
            x(k, :).';

        [~, detail_k] = ...
            robot_model_3d( ...
                t(k), ...
                x_k, ...
                param);

        %% State

        ddq(k, :) = ...
            detail_k.ddq.';

        %% Dynamics

        M_log(:, :, k) = ...
            detail_k.M;

        c_log(k, :) = ...
            detail_k.c.';

        G_log(k, :) = ...
            detail_k.G.';

        command_torque_log(k, :) = ...
            detail_k.tau_command.';

        friction_torque_log(k, :) = ...
            detail_k.tau_fric.';

        contact_torque_log(k, :) = ...
            detail_k.tau_contact.';

        %% Kinematics

        joint_position(k, :) = ...
            detail_k.kinematics.joint.position.';

        joint_velocity(k, :) = ...
            detail_k.kinematics.joint.velocity.';

        ee_position(k, :) = ...
            detail_k.kinematics.ee.position.';

        ee_velocity(k, :) = ...
            detail_k.kinematics.ee.velocity.';

        %% Contact forces

        joint_contact_force(k, :) = ...
            detail_k.contact_force.joint.';

        ee_contact_force(k, :) = ...
            detail_k.contact_force.ee.';

        total_contact_force(k, :) = ...
            detail_k.contact_force.total.';

        %% Contact torques

        joint_contact_torque(k, :) = ...
            detail_k.contact.tau_joint.';

        ee_contact_torque(k, :) = ...
            detail_k.contact.tau_ee.';

        %% Penetration

        joint_penetration(k) = ...
            detail_k.contact.joint.penetration;

        ee_penetration(k) = ...
            detail_k.contact.ee.penetration;

        %% Contact state

        joint_contact_state(k) = ...
            detail_k.contact.joint.is_contact;

        ee_contact_state(k) = ...
            detail_k.contact.ee.is_contact;

        %% Contact components

        joint_contact_spring_force(k) = ...
            detail_k.contact.joint.F_spring;

        joint_contact_damper_force(k) = ...
            detail_k.contact.joint.F_damper;

        ee_contact_spring_force(k) = ...
            detail_k.contact.ee.F_spring;

        ee_contact_damper_force(k) = ...
            detail_k.contact.ee.F_damper;

        %% Friction components

        viscous_friction_torque(k, :) = ...
            detail_k.friction.tau_viscous.';

        coulomb_friction_torque(k, :) = ...
            detail_k.friction.tau_coulomb.';

        %% Energy

        kinetic_energy(k) = ...
            detail_k.energy.kinetic;

        potential_energy(k) = ...
            detail_k.energy.potential;

        mechanical_energy(k) = ...
            detail_k.energy.mechanical;

        friction_power(k) = ...
            detail_k.energy.friction_power;

    end

    %% Store results

    result.t = t;
    result.x = x;

    result.q = q;
    result.dq = dq;
    result.ddq = ddq;

    result.M = M_log;
    result.c = c_log;
    result.G = G_log;

    result.tau_command = ...
        command_torque_log;

    result.tau_fric = ...
        friction_torque_log;

    result.tau_contact = ...
        contact_torque_log;

    result.kinematics.joint.position = ...
        joint_position;

    result.kinematics.joint.velocity = ...
        joint_velocity;

    result.kinematics.ee.position = ...
        ee_position;

    result.kinematics.ee.velocity = ...
        ee_velocity;

    result.contact.force.joint = ...
        joint_contact_force;

    result.contact.force.ee = ...
        ee_contact_force;

    result.contact.force.total = ...
        total_contact_force;

    result.contact.torque.joint = ...
        joint_contact_torque;

    result.contact.torque.ee = ...
        ee_contact_torque;

    result.contact.torque.total = ...
        contact_torque_log;

    result.contact.penetration.joint = ...
        joint_penetration;

    result.contact.penetration.ee = ...
        ee_penetration;

    result.contact.state.joint = ...
        joint_contact_state;

    result.contact.state.ee = ...
        ee_contact_state;

    result.contact.spring_force.joint = ...
        joint_contact_spring_force;

    result.contact.spring_force.ee = ...
        ee_contact_spring_force;

    result.contact.damper_force.joint = ...
        joint_contact_damper_force;

    result.contact.damper_force.ee = ...
        ee_contact_damper_force;

    result.friction.viscous = ...
        viscous_friction_torque;

    result.friction.coulomb = ...
        coulomb_friction_torque;

    result.energy.kinetic = ...
        kinetic_energy;

    result.energy.potential = ...
        potential_energy;

    result.energy.mechanical = ...
        mechanical_energy;

    result.energy.friction_power = ...
        friction_power;

end


function display_simulation_summary_3d(result, param)
%DISPLAY_SIMULATION_SUMMARY_3D
% Display representative numerical simulation results.

    joint_penetration = ...
        result.contact.penetration.joint;

    ee_penetration = ...
        result.contact.penetration.ee;

    joint_contact_force = ...
        result.contact.force.joint;

    ee_contact_force = ...
        result.contact.force.ee;

    total_contact_force = ...
        result.contact.force.total;

    joint_position = ...
        result.kinematics.joint.position;

    ee_position = ...
        result.kinematics.ee.position;

    mechanical_energy = ...
        result.energy.mechanical;

    friction_power = ...
        result.energy.friction_power;

    %% Contact results

    disp('Maximum second-joint penetration [mm]');
    disp(1000 * max(joint_penetration));

    disp('Maximum end-effector penetration [mm]');
    disp(1000 * max(ee_penetration));

    disp('Maximum second-joint normal force [N]');
    disp(max(joint_contact_force(:, 3)));

    disp('Maximum end-effector normal force [N]');
    disp(max(ee_contact_force(:, 3)));

    disp('Maximum total normal force [N]');
    disp(max(total_contact_force(:, 3)));

    %% Final Cartesian position

    disp('Final second-joint position [m]');
    disp(joint_position(end, :));

    disp('Final end-effector position [m]');
    disp(ee_position(end, :));

    disp('Floor height [m]');
    disp(param.z_floor);

    %% Final joint state

    disp('Final joint angles [deg]');
    disp(rad2deg(result.q(end, :)));

    disp('Final joint velocities [rad/s]');
    disp(result.dq(end, :));

    %% Energy

    disp('Initial mechanical energy [J]');
    disp(mechanical_energy(1));

    disp('Final mechanical energy [J]');
    disp(mechanical_energy(end));

    disp('Mechanical-energy decrease [J]');
    disp( ...
        mechanical_energy(1) ...
        - mechanical_energy(end));

    disp('Minimum friction dissipation power [W]');
    disp(min(friction_power));

end


function animate_robot_3d(result, param)
%ANIMATE_ROBOT_3D
% Animate the 3-DOF robot using precalculated results.

    %% Simulation results

    t = ...
        result.t;

    joint_position = ...
        result.kinematics.joint.position;

    ee_position = ...
        result.kinematics.ee.position;

    joint_contact_force = ...
        result.contact.force.joint;

    ee_contact_force = ...
        result.contact.force.ee;

    %% Playback settings

    playback_speed = ...
        param.animation.playback_speed;

    frame_rate = ...
        param.animation.frame_rate;

    force_scale = ...
        param.animation.force_scale;

    animation_time = ...
        t(1): ...
        (playback_speed / frame_rate): ...
        t(end);

    animation_indices = ...
        interp1( ...
            t, ...
            1:length(t), ...
            animation_time, ...
            'nearest');

    animation_indices = ...
        unique(animation_indices);

    %% Figure settings

    total_length = ...
        param.l1 ...
        + param.l2;

    axis_limit = ...
        1.1 ...
        * total_length;

    figure;

    hold on;
    grid on;
    axis equal;

    xlim([
        -axis_limit, ...
         axis_limit
    ]);

    ylim([
        -axis_limit, ...
         axis_limit
    ]);

    zlim([
        min( ...
            -axis_limit, ...
            param.z_floor - 0.1), ...
        axis_limit
    ]);

    xlabel('X [m]');
    ylabel('Y [m]');
    zlabel('Z [m]');

    title('3-DOF robot with surface contact');

    view(45, 25);

    %% Floor

    floor_x = [
        -axis_limit, ...
         axis_limit
    ];

    floor_y = [
        -axis_limit, ...
         axis_limit
    ];

    [floor_X, floor_Y] = ...
        meshgrid( ...
            floor_x, ...
            floor_y);

    floor_Z = ...
        param.z_floor ...
        * ones(size(floor_X));

    surf( ...
        floor_X, ...
        floor_Y, ...
        floor_Z, ...
        'FaceAlpha', 0.20, ...
        'EdgeColor', 'none');

    %% World origin

    plot3( ...
        0, ...
        0, ...
        0, ...
        'o', ...
        'MarkerSize', 9, ...
        'MarkerFaceColor', 'auto');

    %% Initial frame

    k0 = ...
        animation_indices(1);

    p_joint = ...
        joint_position(k0, :);

    p_ee = ...
        ee_position(k0, :);

    link1_plot = plot3( ...
        [0, p_joint(1)], ...
        [0, p_joint(2)], ...
        [0, p_joint(3)], ...
        '-', ...
        'LineWidth', 4);

    link2_plot = plot3( ...
        [p_joint(1), p_ee(1)], ...
        [p_joint(2), p_ee(2)], ...
        [p_joint(3), p_ee(3)], ...
        '-', ...
        'LineWidth', 4);

    joint_plot = plot3( ...
        p_joint(1), ...
        p_joint(2), ...
        p_joint(3), ...
        'o', ...
        'MarkerSize', 9, ...
        'MarkerFaceColor', 'auto');

    ee_plot = plot3( ...
        p_ee(1), ...
        p_ee(2), ...
        p_ee(3), ...
        'o', ...
        'MarkerSize', 9, ...
        'MarkerFaceColor', 'auto');

    trajectory_plot = plot3( ...
        p_ee(1), ...
        p_ee(2), ...
        p_ee(3), ...
        '--', ...
        'LineWidth', 1);

    joint_force_plot = quiver3( ...
        p_joint(1), ...
        p_joint(2), ...
        p_joint(3), ...
        0, ...
        0, ...
        0, ...
        0, ...
        'LineWidth', 2);

    ee_force_plot = quiver3( ...
        p_ee(1), ...
        p_ee(2), ...
        p_ee(3), ...
        0, ...
        0, ...
        0, ...
        0, ...
        'LineWidth', 2);

    time_text = text( ...
        -0.95 * axis_limit, ...
        -0.95 * axis_limit, ...
         0.90 * axis_limit, ...
        sprintf( ...
            't = %.2f s', ...
            t(k0)));

    %% Animation loop

    for frame = 1:length(animation_indices)

        k = ...
            animation_indices(frame);

        p_joint = ...
            joint_position(k, :);

        p_ee = ...
            ee_position(k, :);

        set( ...
            link1_plot, ...
            'XData', ...
            [0, p_joint(1)], ...
            'YData', ...
            [0, p_joint(2)], ...
            'ZData', ...
            [0, p_joint(3)]);

        set( ...
            link2_plot, ...
            'XData', ...
            [p_joint(1), p_ee(1)], ...
            'YData', ...
            [p_joint(2), p_ee(2)], ...
            'ZData', ...
            [p_joint(3), p_ee(3)]);

        set( ...
            joint_plot, ...
            'XData', p_joint(1), ...
            'YData', p_joint(2), ...
            'ZData', p_joint(3));

        set( ...
            ee_plot, ...
            'XData', p_ee(1), ...
            'YData', p_ee(2), ...
            'ZData', p_ee(3));

        set( ...
            trajectory_plot, ...
            'XData', ...
            ee_position(1:k, 1), ...
            'YData', ...
            ee_position(1:k, 2), ...
            'ZData', ...
            ee_position(1:k, 3));

        set( ...
            joint_force_plot, ...
            'XData', p_joint(1), ...
            'YData', p_joint(2), ...
            'ZData', p_joint(3), ...
            'UData', ...
            force_scale ...
            * joint_contact_force(k, 1), ...
            'VData', ...
            force_scale ...
            * joint_contact_force(k, 2), ...
            'WData', ...
            force_scale ...
            * joint_contact_force(k, 3));

        set( ...
            ee_force_plot, ...
            'XData', p_ee(1), ...
            'YData', p_ee(2), ...
            'ZData', p_ee(3), ...
            'UData', ...
            force_scale ...
            * ee_contact_force(k, 1), ...
            'VData', ...
            force_scale ...
            * ee_contact_force(k, 2), ...
            'WData', ...
            force_scale ...
            * ee_contact_force(k, 3));

        set( ...
            time_text, ...
            'String', ...
            sprintf( ...
                [ ...
                    't = %.2f s, ' ...
                    'F_{joint,z} = %.1f N, ' ...
                    'F_{ee,z} = %.1f N' ...
                ], ...
                t(k), ...
                joint_contact_force(k, 3), ...
                ee_contact_force(k, 3)));

        drawnow;

    end

end


function plot_simulation_results_3d(result, param)
%PLOT_SIMULATION_RESULTS_3D
% Plot the main 3-DOF simulation results.

    t = ...
        result.t;

    q = ...
        result.q;

    dq = ...
        result.dq;

    ddq = ...
        result.ddq;

    joint_position = ...
        result.kinematics.joint.position;

    ee_position = ...
        result.kinematics.ee.position;

    joint_contact_force = ...
        result.contact.force.joint;

    ee_contact_force = ...
        result.contact.force.ee;

    total_contact_force = ...
        result.contact.force.total;

    joint_contact_torque = ...
        result.contact.torque.joint;

    ee_contact_torque = ...
        result.contact.torque.ee;

    total_contact_torque = ...
        result.contact.torque.total;

    joint_penetration = ...
        result.contact.penetration.joint;

    ee_penetration = ...
        result.contact.penetration.ee;

    %% Joint angles

    figure;

    plot( ...
        t, ...
        rad2deg(q), ...
        'LineWidth', 1.5);

    grid on;

    xlabel('Time [s]');
    ylabel('Joint angle [deg]');

    legend( ...
        'q_1', ...
        'q_2', ...
        'q_3', ...
        'Location', 'best');

    title('Joint angles with surface contact');

    %% Joint velocities

    figure;

    plot( ...
        t, ...
        dq, ...
        'LineWidth', 1.5);

    grid on;

    xlabel('Time [s]');
    ylabel('Joint velocity [rad/s]');

    legend( ...
        'dq_1', ...
        'dq_2', ...
        'dq_3', ...
        'Location', 'best');

    title('Joint velocities with surface contact');

    %% Joint accelerations

    figure;

    plot( ...
        t, ...
        ddq, ...
        'LineWidth', 1.5);

    grid on;

    xlabel('Time [s]');
    ylabel('Joint acceleration [rad/s^2]');

    legend( ...
        'ddq_1', ...
        'ddq_2', ...
        'ddq_3', ...
        'Location', 'best');

    title('Joint accelerations with surface contact');

    %% Cartesian positions

    figure;

    plot( ...
        t, ...
        ee_position, ...
        'LineWidth', 1.5);

    grid on;

    xlabel('Time [s]');
    ylabel('End-effector position [m]');

    legend( ...
        'X', ...
        'Y', ...
        'Z', ...
        'Location', 'best');

    title('End-effector Cartesian position');

    %% Contact-point heights

    figure;

    plot( ...
        t, ...
        joint_position(:, 3), ...
        'LineWidth', 1.5);

    hold on;

    plot( ...
        t, ...
        ee_position(:, 3), ...
        'LineWidth', 1.5);

    yline( ...
        param.z_floor, ...
        '--', ...
        'Floor');

    grid on;

    xlabel('Time [s]');
    ylabel('Z position [m]');

    legend( ...
        'Second joint', ...
        'End effector', ...
        'Floor', ...
        'Location', 'best');

    title('Contact-point heights');

    %% Penetration

    figure;

    plot( ...
        t, ...
        1000 * joint_penetration, ...
        'LineWidth', 1.5);

    hold on;

    plot( ...
        t, ...
        1000 * ee_penetration, ...
        'LineWidth', 1.5);

    grid on;

    xlabel('Time [s]');
    ylabel('Penetration [mm]');

    legend( ...
        'Second joint', ...
        'End effector', ...
        'Location', 'best');

    title('Surface penetration');

    %% Normal contact forces

    figure;

    plot( ...
        t, ...
        joint_contact_force(:, 3), ...
        'LineWidth', 1.5);

    hold on;

    plot( ...
        t, ...
        ee_contact_force(:, 3), ...
        'LineWidth', 1.5);

    plot( ...
        t, ...
        total_contact_force(:, 3), ...
        '--', ...
        'LineWidth', 1.5);

    grid on;

    xlabel('Time [s]');
    ylabel('Normal contact force [N]');

    legend( ...
        'Second joint', ...
        'End effector', ...
        'Total', ...
        'Location', 'best');

    title('Normal surface-contact forces');

    %% Second-joint contact torque

    figure;

    plot( ...
        t, ...
        joint_contact_torque, ...
        'LineWidth', 1.5);

    grid on;

    xlabel('Time [s]');
    ylabel('Joint torque [Nm]');

    legend( ...
        '\tau_{joint,1}', ...
        '\tau_{joint,2}', ...
        '\tau_{joint,3}', ...
        'Location', 'best');

    title('Torque generated by second-joint contact');

    %% End-effector contact torque

    figure;

    plot( ...
        t, ...
        ee_contact_torque, ...
        'LineWidth', 1.5);

    grid on;

    xlabel('Time [s]');
    ylabel('Joint torque [Nm]');

    legend( ...
        '\tau_{ee,1}', ...
        '\tau_{ee,2}', ...
        '\tau_{ee,3}', ...
        'Location', 'best');

    title('Torque generated by end-effector contact');

    %% Total contact torque

    figure;

    plot( ...
        t, ...
        total_contact_torque, ...
        'LineWidth', 1.5);

    grid on;

    xlabel('Time [s]');
    ylabel('Joint torque [Nm]');

    legend( ...
        '\tau_{contact,1}', ...
        '\tau_{contact,2}', ...
        '\tau_{contact,3}', ...
        'Location', 'best');

    title('Total joint torque generated by contact');

    %% Joint friction torque

    figure;

    plot( ...
        t, ...
        result.tau_fric, ...
        'LineWidth', 1.5);

    grid on;

    xlabel('Time [s]');
    ylabel('Friction torque [Nm]');

    legend( ...
        '\tau_{fric,1}', ...
        '\tau_{fric,2}', ...
        '\tau_{fric,3}', ...
        'Location', 'best');

    title('Joint friction torque');

    %% Gravity torque

    figure;

    plot( ...
        t, ...
        result.G, ...
        'LineWidth', 1.5);

    grid on;

    xlabel('Time [s]');
    ylabel('Gravity torque [Nm]');

    legend( ...
        'G_1', ...
        'G_2', ...
        'G_3', ...
        'Location', 'best');

    title('Gravity torque');

    %% Coriolis and centrifugal torque

    figure;

    plot( ...
        t, ...
        result.c, ...
        'LineWidth', 1.5);

    grid on;

    xlabel('Time [s]');
    ylabel('Torque [Nm]');

    legend( ...
        'c_1', ...
        'c_2', ...
        'c_3', ...
        'Location', 'best');

    title('Coriolis and centrifugal torque');

    %% Mechanical energy

    figure;

    plot( ...
        t, ...
        result.energy.kinetic, ...
        'LineWidth', 1.5);

    hold on;

    plot( ...
        t, ...
        result.energy.potential, ...
        'LineWidth', 1.5);

    plot( ...
        t, ...
        result.energy.mechanical, ...
        'LineWidth', 1.5);

    grid on;

    xlabel('Time [s]');
    ylabel('Energy [J]');

    legend( ...
        'Kinetic energy', ...
        'Potential energy', ...
        'Mechanical energy', ...
        'Location', 'best');

    title('Mechanical energy with contact and friction');

    %% Friction dissipation power

    figure;

    plot( ...
        t, ...
        result.energy.friction_power, ...
        'LineWidth', 1.5);

    grid on;

    xlabel('Time [s]');
    ylabel('Dissipation power [W]');

    title('Mechanical power dissipated by joint friction');

    %% Contact states

    figure;

    stairs( ...
        t, ...
        double(result.contact.state.joint), ...
        'LineWidth', 1.5);

    hold on;

    stairs( ...
        t, ...
        double(result.contact.state.ee), ...
        'LineWidth', 1.5);

    grid on;

    ylim([-0.1, 1.1]);

    xlabel('Time [s]');
    ylabel('Contact state');

    yticks([0, 1]);

    yticklabels({ ...
        'No contact', ...
        'Contact'});

    legend( ...
        'Second joint', ...
        'End effector', ...
        'Location', 'best');

    title('Surface-contact states');

    %% End-effector trajectory

    figure;

    plot3( ...
        ee_position(:, 1), ...
        ee_position(:, 2), ...
        ee_position(:, 3), ...
        'LineWidth', 1.5);

    hold on;

    plot3( ...
        ee_position(1, 1), ...
        ee_position(1, 2), ...
        ee_position(1, 3), ...
        'o', ...
        'MarkerSize', 8, ...
        'MarkerFaceColor', 'auto');

    plot3( ...
        ee_position(end, 1), ...
        ee_position(end, 2), ...
        ee_position(end, 3), ...
        'o', ...
        'MarkerSize', 8, ...
        'MarkerFaceColor', 'auto');

    grid on;
    axis equal;

    xlabel('X [m]');
    ylabel('Y [m]');
    zlabel('Z [m]');

    legend( ...
        'Trajectory', ...
        'Initial position', ...
        'Final position', ...
        'Location', 'best');

    title('End-effector trajectory');

    view(45, 25);

end