function [dx, detail] = robot_model_3d(~, x, param)
%ROBOT_MODEL_3D
% Complete 3-DOF robot model with root yaw.
%
% Joint definition:
%   q1 : Absolute angle of link 1 in the radial-Z plane
%   q2 : Absolute angle of link 2 in the radial-Z plane
%   q3 : Root yaw angle about the world Z axis
%
% State:
%   x = [
%       q1;
%       q2;
%       q3;
%       dq1;
%       dq2;
%       dq3
%   ];
%
% Equation of motion:
%
%   M(q)*ddq
%   + c(q,dq)
%   + G(q)
%   + tau_fric(dq)
%   = tau_command + tau_contact
%
% Input:
%   x:
%       6x1 state vector
%
%   param:
%       Parameter structure generated by robot_parameters_all()
%
% Output:
%   dx:
%       6x1 state-derivative vector
%
%   detail:
%       Structure containing dynamics, kinematics,
%       contact, friction, and energy values.

    %% Input check

    if numel(x) ~= 6
        error('x must contain six states for the 3-DOF model.');
    end

    x = x(:);

    %% State

    q = x(1:3);
    dq = x(4:6);

    %% Kinematics

    kin = robot_kinematics_3d( ...
        q, ...
        dq, ...
        param);

    %% Rigid-body dynamics

    [M, c, G, dynamics_detail] = ...
        rigid_body_dynamics_3d( ...
            q, ...
            dq, ...
            param);

    %% Joint friction

    [tau_fric, friction_detail] = ...
        friction_torque_3d( ...
            dq, ...
            param);

    %% Surface contact

    [F_contact, tau_contact, contact_detail] = ...
        surface_contact_3d( ...
            kin, ...
            param);

    %% Command torque
    %
    % No active controller is applied yet.

    tau_command = zeros(3, 1);

    %% Forward dynamics

    ddq = M \ ( ...
        tau_command ...
        + tau_contact ...
        - c ...
        - G ...
        - tau_fric);

    %% State derivative

    dx = [
        dq;
        ddq
    ];

    %% Energy

    energy = ...
        mechanical_energy_3d( ...
            q, ...
            dq, ...
            M, ...
            tau_fric, ...
            param);

    %% Detail output

    if nargout > 1

        detail.q = q;
        detail.dq = dq;
        detail.ddq = ddq;

        detail.M = M;
        detail.c = c;
        detail.G = G;

        detail.tau_command = tau_command;
        detail.tau_fric = tau_fric;
        detail.tau_contact = tau_contact;

        detail.kinematics = kin;

        detail.contact_force = F_contact;
        detail.contact = contact_detail;

        detail.dynamics = dynamics_detail;
        detail.friction = friction_detail;
        detail.energy = energy;

    end

end


function [M, c, G, detail] = ...
    rigid_body_dynamics_3d(q, dq, param)
%RIGID_BODY_DYNAMICS_3D
% Calculate the 3-DOF rigid-body dynamics terms:
%
%   M(q)     : inertia matrix
%   c(q,dq)  : Coriolis and centrifugal torque vector
%   G(q)     : gravity torque vector
%
% q1 and q2 are absolute link angles.
% q3 rotates the complete planar mechanism about the world Z axis.
%
% Assumption:
%   Each link is approximated as a slender rigid body.
%   Inertia about the link longitudinal axis is neglected.

    %% Joint states

    q1 = q(1);
    q2 = q(2);

    dq1 = dq(1);
    dq2 = dq(2);
    dq3 = dq(3);

    %% Repeated inertia coefficients

    A1_links = ...
        param.I1 ...
        + param.m1 * param.r1^2 ...
        + param.m2 * param.l1^2;

    A2_links = ...
        param.I2 ...
        + param.m2 * param.r2^2;

    coupling = ...
        param.m2 ...
        * param.l1 ...
        * param.r2;

    %% Link inertia matrix

    M11_links = ...
        A1_links;

    M22_links = ...
        A2_links;

    M12_links = ...
        coupling ...
        * cos(q1 - q2);

    % Yaw inertia of the complete moving structure.
    %
    % The horizontal distance from the yaw axis changes
    % with q1 and q2.

    M33_links = ...
        A1_links ...
        * cos(q1)^2 ...
        + A2_links ...
        * cos(q2)^2 ...
        + 2 ...
        * coupling ...
        * cos(q1) ...
        * cos(q2) ...
        + param.I_yaw_base;

    M_links = [
        M11_links, M12_links, 0;
        M12_links, M22_links, 0;
        0,           0,           M33_links
    ];

    %% Reflected motor and gearbox inertia

    M_motor = ...
        diag(param.JM_ref(1:3));

    %% Total inertia matrix

    M = ...
        M_links ...
        + M_motor;

    %% Coriolis and centrifugal torque
    %
    % These terms are consistent with the inertia matrix above.
    %
    % The first two terms include:
    %   - coupling between q1 and q2
    %   - centrifugal effects caused by yaw velocity dq3
    %
    % The third term includes coupling between yaw motion
    % and radial configuration changes.

    c1_planar = ...
        coupling ...
        * sin(q1 - q2) ...
        * dq2^2;

    c1_yaw = ...
        ( ...
            A1_links * cos(q1) ...
            + coupling * cos(q2) ...
        ) ...
        * sin(q1) ...
        * dq3^2;

    c2_planar = ...
        -coupling ...
        * sin(q1 - q2) ...
        * dq1^2;

    c2_yaw = ...
        ( ...
            A2_links * cos(q2) ...
            + coupling * cos(q1) ...
        ) ...
        * sin(q2) ...
        * dq3^2;

    c3 = ...
        -2 ...
        * dq3 ...
        * ( ...
            dq1 ...
            * ( ...
                A1_links * cos(q1) ...
                + coupling * cos(q2) ...
            ) ...
            * sin(q1) ...
            + dq2 ...
            * ( ...
                A2_links * cos(q2) ...
                + coupling * cos(q1) ...
            ) ...
            * sin(q2) ...
        );

    c = [
        c1_planar + c1_yaw;
        c2_planar + c2_yaw;
        c3
    ];

    %% Gravity torque
    %
    % Root yaw q3 rotates about the vertical Z axis.
    % Therefore, gravitational potential energy does not depend on q3.

    G1 = ...
        ( ...
            param.m1 * param.r1 ...
            + param.m2 * param.l1 ...
        ) ...
        * param.g ...
        * cos(q1);

    G2 = ...
        param.m2 ...
        * param.r2 ...
        * param.g ...
        * cos(q2);

    G = [
        G1;
        G2;
        0
    ];

    %% Detail output

    detail.M_links = M_links;
    detail.M_motor = M_motor;

    detail.A1_links = A1_links;
    detail.A2_links = A2_links;
    detail.coupling = coupling;

    detail.M33_links = M33_links;

    detail.c_planar = [
        c1_planar;
        c2_planar;
        0
    ];

    detail.c_yaw = [
        c1_yaw;
        c2_yaw;
        c3
    ];

end


function [tau_fric, detail] = ...
    friction_torque_3d(dq, param)
%FRICTION_TORQUE_3D
% Joint-friction model including:
%
%   1. Viscous friction
%   2. Smooth Coulomb-like friction
%
% The returned torque has the same sign as joint velocity.
% It is subtracted in the forward-dynamics equation.

    %% Friction parameters

    B = param.B(1:3);
    tau_c = param.tau_c(1:3);

    %% Viscous friction

    tau_viscous = ...
        B .* dq;

    %% Smooth Coulomb friction

    tau_coulomb = ...
        tau_c ...
        .* tanh(dq / param.v_s);

    %% Total friction

    tau_fric = ...
        tau_viscous ...
        + tau_coulomb;

    %% Detail output

    detail.tau_viscous = tau_viscous;
    detail.tau_coulomb = tau_coulomb;

end


function [F_contact, tau_contact, detail] = ...
    surface_contact_3d(kin, param)
%SURFACE_CONTACT_3D
% Penalty-based floor contact for:
%
%   1. Second joint
%   2. End effector
%
% Horizontal floor:
%
%   z = param.z_floor
%
% The floor force acts only in the positive world-Z direction.

    %% Second-joint contact state

    z_joint = ...
        kin.joint.position(3);

    vz_joint = ...
        kin.joint.velocity(3);

    [F_joint, joint_detail] = ...
        penalty_contact_point_3d( ...
            z_joint, ...
            vz_joint, ...
            param);

    %% End-effector contact state

    z_ee = ...
        kin.ee.position(3);

    vz_ee = ...
        kin.ee.velocity(3);

    [F_ee, ee_detail] = ...
        penalty_contact_point_3d( ...
            z_ee, ...
            vz_ee, ...
            param);

    %% Convert Cartesian forces to joint torques

    tau_joint = ...
        kin.joint.J.' ...
        * F_joint;

    tau_ee = ...
        kin.ee.J.' ...
        * F_ee;

    tau_contact = ...
        tau_joint ...
        + tau_ee;

    %% Contact-force output

    F_contact.joint = F_joint;
    F_contact.ee = F_ee;

    F_contact.total = ...
        F_joint ...
        + F_ee;

    %% Detail output

    detail.joint.position = ...
        kin.joint.position;

    detail.joint.velocity = ...
        kin.joint.velocity;

    detail.joint.penetration = ...
        joint_detail.penetration;

    detail.joint.penetration_velocity = ...
        joint_detail.penetration_velocity;

    detail.joint.F_spring = ...
        joint_detail.F_spring;

    detail.joint.F_damper = ...
        joint_detail.F_damper;

    detail.joint.is_contact = ...
        joint_detail.is_contact;

    detail.ee.position = ...
        kin.ee.position;

    detail.ee.velocity = ...
        kin.ee.velocity;

    detail.ee.penetration = ...
        ee_detail.penetration;

    detail.ee.penetration_velocity = ...
        ee_detail.penetration_velocity;

    detail.ee.F_spring = ...
        ee_detail.F_spring;

    detail.ee.F_damper = ...
        ee_detail.F_damper;

    detail.ee.is_contact = ...
        ee_detail.is_contact;

    detail.tau_joint = tau_joint;
    detail.tau_ee = tau_ee;
    detail.tau_total = tau_contact;

end


function [F_contact, detail] = ...
    penalty_contact_point_3d(z_point, vz_point, param)
%PENALTY_CONTACT_POINT_3D
% Penalty contact model for one point against a horizontal floor.
%
% Penetration:
%
%   penetration = z_floor - z_point
%
% Normal force:
%
%   Fz = k*penetration - d*vz
%
% The floor can push the robot but cannot pull it.

    %% Penetration

    penetration = ...
        param.z_floor ...
        - z_point;

    penetration_velocity = ...
        -vz_point;

    %% Normal contact force

    if penetration > 0

        F_spring = ...
            param.k_contact ...
            * penetration;

        F_damper = ...
            param.d_contact ...
            * penetration_velocity;

        Fz = ...
            F_spring ...
            + F_damper;

        Fz = ...
            max( ...
                Fz, ...
                param.contact_force_min);

    else

        F_spring = 0;
        F_damper = 0;
        Fz = 0;

    end

    %% Cartesian force in world coordinates

    F_contact = [
        0;
        0;
        Fz
    ];

    %% Detail output

    detail.penetration = ...
        max(penetration, 0);

    detail.penetration_velocity = ...
        penetration_velocity;

    detail.F_spring = F_spring;
    detail.F_damper = F_damper;
    detail.is_contact = Fz > 0;

end


function energy = ...
    mechanical_energy_3d(q, dq, M, tau_fric, param)
%MECHANICAL_ENERGY_3D
% Calculate kinetic energy, gravitational potential energy,
% total mechanical energy, and friction-dissipation power.

    %% Kinetic energy

    kinetic = ...
        0.5 ...
        * dq.' ...
        * M ...
        * dq;

    %% Gravitational potential energy
    %
    % Potential energy does not depend on q3 because
    % q3 is rotation about the vertical axis.

    potential_link1 = ...
        param.m1 ...
        * param.g ...
        * param.r1 ...
        * sin(q(1));

    potential_link2 = ...
        param.m2 ...
        * param.g ...
        * ( ...
            param.l1 * sin(q(1)) ...
            + param.r2 * sin(q(2)) ...
        );

    potential = ...
        potential_link1 ...
        + potential_link2;

    %% Total mechanical energy

    mechanical = ...
        kinetic ...
        + potential;

    %% Friction-dissipation power

    friction_power = ...
        dq.' ...
        * tau_fric;

    %% Output

    energy.kinetic = kinetic;
    energy.potential = potential;
    energy.mechanical = mechanical;
    energy.friction_power = friction_power;

end