function [dx, detail] = robot_model_3d(t, x, param)
%ROBOT_MODEL_3D
% Complete 3-DOF robot model with Cartesian KD control
% and an external sinusoidal force.
%
% Joint definition:
%   q1 : Absolute angle of link 1 in the radial-Z plane
%   q2 : Absolute angle of link 2 in the radial-Z plane
%   q3 : Root yaw angle about the world Z axis
%
% State:
%
%   x = [
%       q1;
%       q2;
%       q3;
%       dq1;
%       dq2;
%       dq3
%   ]
%
% Cartesian control law:
%
%   F_control
%       = K * (p_ref - p)
%       - D * dp
%
%   tau_control
%       = J_ee.' * F_control
%
% External Cartesian force:
%
%   F_external = [
%       0;
%       0;
%       F_external_z
%   ]
%
%   tau_external
%       = J_ee.' * F_external
%
% Equation of motion:
%
%   M(q)*ddq
%   + c(q,dq)
%   + G(q)
%   + tau_fric(dq)
%   =
%       tau_control
%       + tau_external
%       + tau_contact
%
% Input:
%   t:
%       Simulation time [s]
%
%   x:
%       6x1 state vector
%
%   param:
%       Parameter structure generated by robot_parameters_all()
%
% Output:
%   dx:
%       6x1 state-derivative vector
%
%   detail:
%       Structure containing dynamics, control,
%       external-force, contact, friction,
%       kinematics, and energy values.

    %% Input check

    if numel(x) ~= 6
        error('x must contain six states for the 3-DOF model.');
    end

    x = x(:);

    %% State

    q = ...
        x(1:3);

    dq = ...
        x(4:6);

    %% Kinematics

    kin = ...
        robot_kinematics_3d( ...
            q, ...
            dq, ...
            param);

    %% Rigid-body dynamics

    [M, c, G, dynamics_detail] = ...
        rigid_body_dynamics_3d( ...
            q, ...
            dq, ...
            param);

    %% Joint friction

    [tau_fric, friction_detail] = ...
        friction_torque_3d( ...
            dq, ...
            param);

    %% Cartesian KD control

    [F_control, tau_control, control_detail] = ...
        cartesian_kd_control_3d( ...
            kin, ...
            param);

    %% External sinusoidal force

    [F_external, tau_external, external_force_detail] = ...
        external_sinusoidal_force_3d( ...
            t, ...
            kin, ...
            param);

    %% Surface contact

    contact_enabled = ...
        param.contact.enabled;

    if contact_enabled

        [F_contact, tau_contact, contact_detail] = ...
            surface_contact_3d( ...
                kin, ...
                param);

    end

    %% Command torque
    %
    % tau_command contains only the controller-generated torque.
    % The external-force torque is stored separately.

    tau_command = ...
        tau_control;

    %% Forward dynamics

    applied_torque = ...
        tau_control ...
        + tau_external;

    if contact_enabled
        applied_torque = ...
            applied_torque ...
            + tau_contact;
    end

    ddq = ...
        M \ ( ...
            applied_torque ...
            - c ...
            - G ...
            - tau_fric);

    %% State derivative

    dx = [
        dq;
        ddq
    ];

    %% Energy

    energy = ...
        mechanical_energy_3d( ...
            q, ...
            dq, ...
            M, ...
            tau_fric, ...
            param);

    %% Detail output

    if nargout > 1

        detail.q = q;
        detail.dq = dq;
        detail.ddq = ddq;

        detail.M = M;
        detail.c = c;
        detail.G = G;

        detail.tau_command = ...
            tau_command;

        detail.tau_control = ...
            tau_control;

        detail.tau_external = ...
            tau_external;

        detail.tau_fric = ...
            tau_fric;

        detail.control_force = ...
            F_control;

        detail.external_force = ...
            F_external;

        detail.kinematics = ...
            kin;

        detail.control = ...
            control_detail;

        detail.external = ...
            external_force_detail;

        if contact_enabled
            detail.tau_contact = ...
                tau_contact;

            detail.contact_force = ...
                F_contact;

            detail.contact = ...
                contact_detail;
        end

        detail.dynamics = ...
            dynamics_detail;

        detail.friction = ...
            friction_detail;

        detail.energy = ...
            energy;

    end

end


function [F_control, tau_control, detail] = ...
    cartesian_kd_control_3d(kin, param)
%CARTESIAN_KD_CONTROL_3D
% Cartesian end-effector KD control in world XYZ coordinates.
%
% Control law:
%
%   F_control
%       = K * (p_ref - p)
%       - D * dp
%
% Joint torque:
%
%   tau_control
%       = J_ee.' * F_control

    %% Default output

    F_control = ...
        zeros(3, 1);

    tau_control = ...
        zeros(3, 1);

    position_reference = ...
        zeros(3, 1);

    position_error = ...
        zeros(3, 1);

    proportional_force = ...
        zeros(3, 1);

    damping_force = ...
        zeros(3, 1);

    %% Control state

    control_enabled = false;

    if isfield(param, 'control') ...
            && isfield(param.control, 'enabled')

        control_enabled = ...
            param.control.enabled;

    end

    %% Cartesian KD control

    if control_enabled

        if ~isfield(param.control, 'position_reference')
            error( ...
                ['param.control.position_reference ', ...
                 'has not been defined.']);
        end

        position_reference = ...
            param.control.position_reference(:);

        if numel(position_reference) ~= 3
            error( ...
                ['param.control.position_reference ', ...
                 'must contain X, Y, and Z.']);
        end

        if any(~isfinite(position_reference))
            error( ...
                ['param.control.position_reference contains ', ...
                 'NaN or Inf. Set it from the initial ', ...
                 'end-effector position in main_MCGFC_3d.']);
        end

        if ~isequal(size(param.control.K), [3, 3])
            error('param.control.K must be a 3x3 matrix.');
        end

        if ~isequal(size(param.control.D), [3, 3])
            error('param.control.D must be a 3x3 matrix.');
        end

        position_error = ...
            position_reference ...
            - kin.ee.position;

        proportional_force = ...
            param.control.K ...
            * position_error;

        damping_force = ...
            -param.control.D ...
            * kin.ee.velocity;

        F_control = ...
            proportional_force ...
            + damping_force;

        tau_control = ...
            kin.ee.J.' ...
            * F_control;

    end

    %% Detail output

    detail.enabled = ...
        control_enabled;

    detail.position_reference = ...
        position_reference;

    detail.position = ...
        kin.ee.position;

    detail.velocity = ...
        kin.ee.velocity;

    detail.position_error = ...
        position_error;

    detail.proportional_force = ...
        proportional_force;

    detail.damping_force = ...
        damping_force;

    detail.force = ...
        F_control;

    detail.torque = ...
        tau_control;

end


function [F_external, tau_external, detail] = ...
    external_sinusoidal_force_3d(t, kin, param)
%EXTERNAL_SINUSOIDAL_FORCE_3D
% Apply a sinusoidal external force to the end effector
% along the world-Z direction.
%
%   Fz = A * sin(2*pi*f*(t - start_time) + phase)
%
% The force is zero before start_time.

    %% Default output

    F_external = ...
        zeros(3, 1);

    tau_external = ...
        zeros(3, 1);

    Fz = 0;

    elapsed_time = 0;

    %% External-force state

    external_force_enabled = false;

    if isfield(param, 'external_force') ...
            && isfield(param.external_force, 'enabled')

        external_force_enabled = ...
            param.external_force.enabled;

    end

    %% Sinusoidal external force

    if external_force_enabled

        start_time = ...
            param.external_force.start_time;

        if t >= start_time

            elapsed_time = ...
                t ...
                - start_time;

            amplitude = ...
                param.external_force.amplitude;

            frequency = ...
                param.external_force.frequency;

            phase = ...
                param.external_force.phase;

            Fz = ...
                amplitude ...
                * sin( ...
                    2 ...
                    * pi ...
                    * frequency ...
                    * elapsed_time ...
                    + phase);

        end

        F_external = [
            0;
            0;
            Fz
        ];

        tau_external = ...
            kin.ee.J.' ...
            * F_external;

    end

    %% Detail output

    detail.enabled = ...
        external_force_enabled;

    detail.elapsed_time = ...
        elapsed_time;

    detail.force_z = ...
        Fz;

    detail.force = ...
        F_external;

    detail.torque = ...
        tau_external;

end


function [M, c, G, detail] = ...
    rigid_body_dynamics_3d(q, dq, param)
%RIGID_BODY_DYNAMICS_3D
% Calculate the 3-DOF rigid-body dynamics terms:
%
%   M(q)     : inertia matrix
%   c(q,dq)  : Coriolis and centrifugal torque vector
%   G(q)     : gravity torque vector
%
% q1 and q2 are absolute link angles.
% q3 rotates the complete planar mechanism about the world Z axis.
%
% Assumption:
%   Each link is approximated as a slender rigid body.
%   Inertia about the link longitudinal axis is neglected.

    %% Joint states

    q1 = q(1);
    q2 = q(2);

    dq1 = dq(1);
    dq2 = dq(2);
    dq3 = dq(3);

    %% Repeated inertia coefficients

    A1_links = ...
        param.I1 ...
        + param.m1 * param.r1^2 ...
        + param.m2 * param.l1^2;

    A2_links = ...
        param.I2 ...
        + param.m2 * param.r2^2;

    coupling = ...
        param.m2 ...
        * param.l1 ...
        * param.r2;

    %% Link inertia matrix

    M11_links = ...
        A1_links;

    M22_links = ...
        A2_links;

    M12_links = ...
        coupling ...
        * cos(q1 - q2);

    % Yaw inertia of the complete moving structure.
    %
    % The horizontal distance from the yaw axis changes
    % with q1 and q2.

    M33_links = ...
        A1_links ...
        * cos(q1)^2 ...
        + A2_links ...
        * cos(q2)^2 ...
        + 2 ...
        * coupling ...
        * cos(q1) ...
        * cos(q2) ...
        + param.I_yaw_base;

    M_links = [
        M11_links, M12_links, 0;
        M12_links, M22_links, 0;
        0,           0,           M33_links
    ];

    %% Reflected motor and gearbox inertia

    M_motor = ...
        diag(param.JM_ref(1:3));

    %% Total inertia matrix

    M = ...
        M_links ...
        + M_motor;

    %% Coriolis and centrifugal torque
    %
    % These terms are consistent with the inertia matrix above.
    %
    % The first two terms include:
    %   - coupling between q1 and q2
    %   - centrifugal effects caused by yaw velocity dq3
    %
    % The third term includes coupling between yaw motion
    % and radial configuration changes.

    c1_planar = ...
        coupling ...
        * sin(q1 - q2) ...
        * dq2^2;

    c1_yaw = ...
        ( ...
            A1_links * cos(q1) ...
            + coupling * cos(q2) ...
        ) ...
        * sin(q1) ...
        * dq3^2;

    c2_planar = ...
        -coupling ...
        * sin(q1 - q2) ...
        * dq1^2;

    c2_yaw = ...
        ( ...
            A2_links * cos(q2) ...
            + coupling * cos(q1) ...
        ) ...
        * sin(q2) ...
        * dq3^2;

    c3 = ...
        -2 ...
        * dq3 ...
        * ( ...
            dq1 ...
            * ( ...
                A1_links * cos(q1) ...
                + coupling * cos(q2) ...
            ) ...
            * sin(q1) ...
            + dq2 ...
            * ( ...
                A2_links * cos(q2) ...
                + coupling * cos(q1) ...
            ) ...
            * sin(q2) ...
        );

    c = [
        c1_planar + c1_yaw;
        c2_planar + c2_yaw;
        c3
    ];

    %% Gravity torque
    %
    % Root yaw q3 rotates about the vertical Z axis.
    % Therefore, gravitational potential energy does not depend on q3.

    G1 = ...
        ( ...
            param.m1 * param.r1 ...
            + param.m2 * param.l1 ...
        ) ...
        * param.g ...
        * cos(q1);

    G2 = ...
        param.m2 ...
        * param.r2 ...
        * param.g ...
        * cos(q2);

    G = [
        G1;
        G2;
        0
    ];

    %% Detail output

    detail.M_links = M_links;
    detail.M_motor = M_motor;

    detail.A1_links = A1_links;
    detail.A2_links = A2_links;
    detail.coupling = coupling;

    detail.M33_links = M33_links;

    detail.c_planar = [
        c1_planar;
        c2_planar;
        0
    ];

    detail.c_yaw = [
        c1_yaw;
        c2_yaw;
        c3
    ];

end


function [tau_fric, detail] = ...
    friction_torque_3d(dq, param)
%FRICTION_TORQUE_3D
% Joint-friction model including:
%
%   1. Viscous friction
%   2. Smooth Coulomb-like friction
%
% The returned torque has the same sign as joint velocity.
% It is subtracted in the forward-dynamics equation.

    %% Friction parameters

    B = param.B(1:3);
    tau_c = param.tau_c(1:3);

    %% Viscous friction

    tau_viscous = ...
        B .* dq;

    %% Smooth Coulomb friction

    tau_coulomb = ...
        tau_c ...
        .* tanh(dq / param.v_s);

    %% Total friction

    tau_fric = ...
        tau_viscous ...
        + tau_coulomb;

    %% Detail output

    detail.tau_viscous = tau_viscous;
    detail.tau_coulomb = tau_coulomb;

end


function [F_contact, tau_contact, detail] = ...
    surface_contact_3d(kin, param)
%SURFACE_CONTACT_3D
% Penalty-based floor contact for:
%
%   1. Second joint
%   2. End effector
%
% Horizontal floor:
%
%   z = param.z_floor
%
% The floor force acts only in the positive world-Z direction.

    %% Second-joint contact state

    z_joint = ...
        kin.joint.position(3);

    vz_joint = ...
        kin.joint.velocity(3);

    [F_joint, joint_detail] = ...
        penalty_contact_point_3d( ...
            z_joint, ...
            vz_joint, ...
            param);

    %% End-effector contact state

    z_ee = ...
        kin.ee.position(3);

    vz_ee = ...
        kin.ee.velocity(3);

    [F_ee, ee_detail] = ...
        penalty_contact_point_3d( ...
            z_ee, ...
            vz_ee, ...
            param);

    %% Convert Cartesian forces to joint torques

    tau_joint = ...
        kin.joint.J.' ...
        * F_joint;

    tau_ee = ...
        kin.ee.J.' ...
        * F_ee;

    tau_contact = ...
        tau_joint ...
        + tau_ee;

    %% Contact-force output

    F_contact.joint = F_joint;
    F_contact.ee = F_ee;

    F_contact.total = ...
        F_joint ...
        + F_ee;

    %% Detail output

    detail.joint.position = ...
        kin.joint.position;

    detail.joint.velocity = ...
        kin.joint.velocity;

    detail.joint.penetration = ...
        joint_detail.penetration;

    detail.joint.penetration_velocity = ...
        joint_detail.penetration_velocity;

    detail.joint.F_spring = ...
        joint_detail.F_spring;

    detail.joint.F_damper = ...
        joint_detail.F_damper;

    detail.joint.is_contact = ...
        joint_detail.is_contact;

    detail.ee.position = ...
        kin.ee.position;

    detail.ee.velocity = ...
        kin.ee.velocity;

    detail.ee.penetration = ...
        ee_detail.penetration;

    detail.ee.penetration_velocity = ...
        ee_detail.penetration_velocity;

    detail.ee.F_spring = ...
        ee_detail.F_spring;

    detail.ee.F_damper = ...
        ee_detail.F_damper;

    detail.ee.is_contact = ...
        ee_detail.is_contact;

    detail.tau_joint = tau_joint;
    detail.tau_ee = tau_ee;
    detail.tau_total = tau_contact;

end


function [F_contact, detail] = ...
    penalty_contact_point_3d(z_point, vz_point, param)
%PENALTY_CONTACT_POINT_3D
% Penalty contact model for one point against a horizontal floor.
%
% Penetration:
%
%   penetration = z_floor - z_point
%
% Normal force:
%
%   Fz = k*penetration - d*vz
%
% The floor can push the robot but cannot pull it.

    %% Penetration

    penetration = ...
        param.z_floor ...
        - z_point;

    penetration_velocity = ...
        -vz_point;

    %% Normal contact force

    if penetration > 0

        F_spring = ...
            param.k_contact ...
            * penetration;

        F_damper = ...
            param.d_contact ...
            * penetration_velocity;

        Fz = ...
            F_spring ...
            + F_damper;

        Fz = ...
            max( ...
                Fz, ...
                param.contact_force_min);

    else

        F_spring = 0;
        F_damper = 0;
        Fz = 0;

    end

    %% Cartesian force in world coordinates

    F_contact = [
        0;
        0;
        Fz
    ];

    %% Detail output

    detail.penetration = ...
        max(penetration, 0);

    detail.penetration_velocity = ...
        penetration_velocity;

    detail.F_spring = F_spring;
    detail.F_damper = F_damper;
    detail.is_contact = Fz > 0;

end


function energy = ...
    mechanical_energy_3d(q, dq, M, tau_fric, param)
%MECHANICAL_ENERGY_3D
% Calculate kinetic energy, gravitational potential energy,
% total mechanical energy, and friction-dissipation power.

    %% Kinetic energy

    kinetic = ...
        0.5 ...
        * dq.' ...
        * M ...
        * dq;

    %% Gravitational potential energy
    %
    % Potential energy does not depend on q3 because
    % q3 is rotation about the vertical axis.

    potential_link1 = ...
        param.m1 ...
        * param.g ...
        * param.r1 ...
        * sin(q(1));

    potential_link2 = ...
        param.m2 ...
        * param.g ...
        * ( ...
            param.l1 * sin(q(1)) ...
            + param.r2 * sin(q(2)) ...
        );

    potential = ...
        potential_link1 ...
        + potential_link2;

    %% Total mechanical energy

    mechanical = ...
        kinetic ...
        + potential;

    %% Friction-dissipation power

    friction_power = ...
        dq.' ...
        * tau_fric;

    %% Output

    energy.kinetic = kinetic;
    energy.potential = potential;
    energy.mechanical = mechanical;
    energy.friction_power = friction_power;

end
