function [dx, detail] = robot_model_2d(~, x, param)
%ROBOT_MODEL_2D
% Complete planar 2-DOF robot model.
%
% This function calculates:
%   1. Rigid-body dynamics
%   2. Joint friction
%   3. Surface-contact forces
%   4. Joint accelerations
%   5. State derivatives
%
% State:
%   x = [
%       q1;
%       q2;
%       dq1;
%       dq2
%   ];
%
% Equation of motion:
%
%   M(q)*ddq
%   + c(q,dq)
%   + G(q)
%   + tau_fric(dq)
%   = tau_command + tau_contact
%
% Input:
%   x:
%       4x1 state vector
%
%   param:
%       Parameter structure generated by robot_parameters_all()
%
% Output:
%   dx:
%       4x1 state-derivative vector
%
%   detail:
%       Structure containing intermediate dynamics,
%       kinematics, contact, and energy values.

    %% Input check

    if numel(x) ~= 4
        error('x must contain four states for the 2-DOF model.');
    end

    x = x(:);

    %% State

    q = x(1:2);
    dq = x(3:4);

    %% Kinematics

    kin = robot_kinematics_2d( ...
        q, ...
        dq, ...
        param);

    %% Rigid-body dynamics

    [M, c, G, dynamics_detail] = ...
        rigid_body_dynamics_2d( ...
            q, ...
            dq, ...
            param);

    %% Joint friction

    [tau_fric, friction_detail] = ...
        friction_torque_2d( ...
            dq, ...
            param);

    %% Surface contact

    [F_contact, tau_contact, contact_detail] = ...
        surface_contact_2d( ...
            kin, ...
            param);

    %% Command torque
    %
    % Currently no active control torque is applied.
    % This section can later be replaced by a controller.

    tau_command = zeros(2, 1);

    %% Forward dynamics

    ddq = M \ ( ...
        tau_command ...
        + tau_contact ...
        - c ...
        - G ...
        - tau_fric);

    %% State derivative

    dx = [
        dq;
        ddq
    ];

    %% Energy

    energy = ...
        mechanical_energy_2d( ...
            q, ...
            dq, ...
            M, ...
            tau_fric, ...
            param);

    %% Detail output

    if nargout > 1

        detail.q = q;
        detail.dq = dq;
        detail.ddq = ddq;

        detail.M = M;
        detail.c = c;
        detail.G = G;

        detail.tau_command = tau_command;
        detail.tau_fric = tau_fric;
        detail.tau_contact = tau_contact;

        detail.kinematics = kin;
        detail.contact_force = F_contact;
        detail.contact = contact_detail;

        detail.dynamics = dynamics_detail;
        detail.friction = friction_detail;
        detail.energy = energy;

    end

end


function [M, c, G, detail] = ...
    rigid_body_dynamics_2d(q, dq, param)
%RIGID_BODY_DYNAMICS_2D
% Calculate the planar rigid-body dynamics terms:
%
%   M(q)     : inertia matrix
%   c(q,dq)  : Coriolis and centrifugal torque vector
%   G(q)     : gravity torque vector
%
% q1 and q2 are absolute link angles measured from the +X axis.

    %% State

    q1 = q(1);
    q2 = q(2);

    dq1 = dq(1);
    dq2 = dq(2);

    %% Rigid-link inertia matrix

    M11_links = ...
        param.I1 ...
        + param.m1 * param.r1^2 ...
        + param.m2 * param.l1^2;

    M22_links = ...
        param.I2 ...
        + param.m2 * param.r2^2;

    coupling = ...
        param.m2 ...
        * param.l1 ...
        * param.r2;

    M12_links = ...
        coupling ...
        * cos(q1 - q2);

    M_links = [
        M11_links, M12_links;
        M12_links, M22_links
    ];

    %% Reflected motor and gearbox inertia

    M_motor = diag( ...
        param.JM_ref(1:2));

    %% Total inertia matrix

    M = ...
        M_links ...
        + M_motor;

    %% Coriolis and centrifugal torque

    c = [
         coupling ...
         * sin(q1 - q2) ...
         * dq2^2;

        -coupling ...
         * sin(q1 - q2) ...
         * dq1^2
    ];

    %% Gravity torque

    G1 = ...
        ( ...
            param.m1 * param.r1 ...
            + param.m2 * param.l1 ...
        ) ...
        * param.g ...
        * cos(q1);

    G2 = ...
        param.m2 ...
        * param.r2 ...
        * param.g ...
        * cos(q2);

    G = [
        G1;
        G2
    ];

    %% Detail output

    detail.M_links = M_links;
    detail.M_motor = M_motor;
    detail.coupling = coupling;

end


function [tau_fric, detail] = ...
    friction_torque_2d(dq, param)
%FRICTION_TORQUE_2D
% Joint-friction model including:
%
%   1. Viscous friction
%   2. Smooth Coulomb-like friction
%
% The returned torque has the same sign as joint velocity.
% It is subtracted in the forward-dynamics equation.

    %% 2-DOF friction parameters

    B = param.B(1:2);
    tau_c = param.tau_c(1:2);

    %% Viscous friction

    tau_viscous = ...
        B .* dq;

    %% Smooth Coulomb friction

    tau_coulomb = ...
        tau_c ...
        .* tanh(dq / param.v_s);

    %% Total friction

    tau_fric = ...
        tau_viscous ...
        + tau_coulomb;

    %% Detail output

    detail.tau_viscous = tau_viscous;
    detail.tau_coulomb = tau_coulomb;

end


function [F_contact, tau_contact, detail] = ...
    surface_contact_2d(kin, param)
%SURFACE_CONTACT_2D
% Penalty-based floor contact for:
%
%   1. Second joint
%   2. End effector
%
% Horizontal floor:
%
%   z = param.z_floor
%
% The kinematic positions, velocities, and Jacobians are supplied
% by robot_kinematics_2d().

    %% Second-joint contact

    z_joint = ...
        kin.joint.position(2);

    vz_joint = ...
        kin.joint.velocity(2);

    [F_joint, joint_detail] = ...
        penalty_contact_point_2d( ...
            z_joint, ...
            vz_joint, ...
            param);

    %% End-effector contact

    z_ee = ...
        kin.ee.position(2);

    vz_ee = ...
        kin.ee.velocity(2);

    [F_ee, ee_detail] = ...
        penalty_contact_point_2d( ...
            z_ee, ...
            vz_ee, ...
            param);

    %% Convert Cartesian forces to joint torques

    tau_joint = ...
        kin.joint.J.' ...
        * F_joint;

    tau_ee = ...
        kin.ee.J.' ...
        * F_ee;

    tau_contact = ...
        tau_joint ...
        + tau_ee;

    %% Contact-force output

    F_contact.joint = F_joint;
    F_contact.ee = F_ee;

    F_contact.total = ...
        F_joint ...
        + F_ee;

    %% Detail output

    detail.joint.position = ...
        kin.joint.position;

    detail.joint.velocity = ...
        kin.joint.velocity;

    detail.joint.penetration = ...
        joint_detail.penetration;

    detail.joint.penetration_velocity = ...
        joint_detail.penetration_velocity;

    detail.joint.F_spring = ...
        joint_detail.F_spring;

    detail.joint.F_damper = ...
        joint_detail.F_damper;

    detail.joint.is_contact = ...
        joint_detail.is_contact;

    detail.ee.position = ...
        kin.ee.position;

    detail.ee.velocity = ...
        kin.ee.velocity;

    detail.ee.penetration = ...
        ee_detail.penetration;

    detail.ee.penetration_velocity = ...
        ee_detail.penetration_velocity;

    detail.ee.F_spring = ...
        ee_detail.F_spring;

    detail.ee.F_damper = ...
        ee_detail.F_damper;

    detail.ee.is_contact = ...
        ee_detail.is_contact;

    detail.tau_joint = tau_joint;
    detail.tau_ee = tau_ee;
    detail.tau_total = tau_contact;

end


function [F_contact, detail] = ...
    penalty_contact_point_2d(z_point, vz_point, param)
%PENALTY_CONTACT_POINT_2D
% Penalty contact model for one point against a horizontal floor.
%
% Penetration:
%
%   penetration = z_floor - z_point
%
% Contact force:
%
%   Fz = k*penetration - d*vz
%
% The floor can push the robot but cannot pull it.

    %% Penetration

    penetration = ...
        param.z_floor ...
        - z_point;

    penetration_velocity = ...
        -vz_point;

    %% Contact force

    if penetration > 0

        F_spring = ...
            param.k_contact ...
            * penetration;

        F_damper = ...
            param.d_contact ...
            * penetration_velocity;

        Fz = ...
            F_spring ...
            + F_damper;

        Fz = ...
            max( ...
                Fz, ...
                param.contact_force_min);

    else

        F_spring = 0;
        F_damper = 0;
        Fz = 0;

    end

    %% Cartesian force in the X-Z plane

    F_contact = [
        0;
        Fz
    ];

    %% Detail output

    detail.penetration = ...
        max(penetration, 0);

    detail.penetration_velocity = ...
        penetration_velocity;

    detail.F_spring = F_spring;
    detail.F_damper = F_damper;
    detail.is_contact = Fz > 0;

end


function energy = ...
    mechanical_energy_2d(q, dq, M, tau_fric, param)
%MECHANICAL_ENERGY_2D
% Calculate kinetic energy, gravitational potential energy,
% total mechanical energy, and friction-dissipation power.

    %% Kinetic energy

    kinetic = ...
        0.5 ...
        * dq.' ...
        * M ...
        * dq;

    %% Gravitational potential energy

    potential_link1 = ...
        param.m1 ...
        * param.g ...
        * param.r1 ...
        * sin(q(1));

    potential_link2 = ...
        param.m2 ...
        * param.g ...
        * ( ...
            param.l1 * sin(q(1)) ...
            + param.r2 * sin(q(2)) ...
        );

    potential = ...
        potential_link1 ...
        + potential_link2;

    %% Total mechanical energy

    mechanical = ...
        kinetic ...
        + potential;

    %% Friction-dissipation power
    %
    % This value is nonnegative because tau_fric has the same
    % direction as dq and is subtracted from the equation of motion.

    friction_power = ...
        dq.' ...
        * tau_fric;

    %% Output

    energy.kinetic = kinetic;
    energy.potential = potential;
    energy.mechanical = mechanical;
    energy.friction_power = friction_power;

end