function [F_contact, tau_contact, detail] = ...
    surface_contact_force(q, dq, param)
%SURFACE_CONTACT_FORCE Penalty-based contact with a horizontal surface.
%
% The surface is located at:
%   z = param.z_floor
%
% Only the end effector is considered for contact.
%
% Contact model:
%   penetration = z_floor - z_ee
%
% If penetration > 0:
%   Fz = k_contact * penetration ...
%      + d_contact * penetration_velocity
%
% The contact force is prevented from becoming attractive.
%
% Outputs:
%   F_contact   : Cartesian contact force [Fx; Fz] [N]
%   tau_contact : Joint contact torque J' * F_contact [Nm]
%   detail      : Contact-state information

    %% Joint states

    q1 = q(1);
    q2 = q(2);

    %% End-effector position

    x_ee = ...
        param.l1 * cos(q1) ...
        + param.l2 * cos(q2);

    z_ee = ...
        param.l1 * sin(q1) ...
        + param.l2 * sin(q2);

    %% End-effector Jacobian
    %
    % q1 and q2 are absolute link angles.

    J = [
        -param.l1 * sin(q1), ...
        -param.l2 * sin(q2);

         param.l1 * cos(q1), ...
         param.l2 * cos(q2)
    ];

    %% End-effector velocity

    v_ee = J * dq;

    vx_ee = v_ee(1);
    vz_ee = v_ee(2);

    %% Penetration state

    penetration = ...
        param.z_floor - z_ee;

    penetration_velocity = ...
        -vz_ee;

    %% Contact force

    if penetration > 0

        F_spring = ...
            param.k_contact * penetration;

        F_damper = ...
            param.d_contact * penetration_velocity;

        Fz = F_spring + F_damper;

        % The surface can push but cannot pull.
        Fz = max(Fz, 0);

    else

        F_spring = 0;
        F_damper = 0;
        Fz = 0;

    end

    F_contact = [
        0;
        Fz
    ];

    %% Joint torque generated by contact

    tau_contact = ...
        J.' * F_contact;

    %% Detail output

    detail.x_ee = x_ee;
    detail.z_ee = z_ee;

    detail.vx_ee = vx_ee;
    detail.vz_ee = vz_ee;

    detail.penetration = max(penetration, 0);
    detail.penetration_velocity = penetration_velocity;

    detail.F_spring = F_spring;
    detail.F_damper = F_damper;

    detail.is_contact = Fz > 0;

end