function [F_contact, tau_contact, detail] = ...
    surface_contact_force(q, dq, param)
%SURFACE_CONTACT_FORCE
% Penalty-based contact for:
%   1. Second joint
%   2. End effector
%
% Horizontal floor:
%   z = param.z_floor
%
% Output:
%   F_contact:
%       struct containing Cartesian contact forces
%
%   tau_contact:
%       total joint torque generated by all contacts
%
%   detail:
%       contact positions, penetration, and states

    %% Joint states

    q1 = q(1);
    q2 = q(2);

    %% Forward kinematics
    %
    % The current dynamics model is planar.
    % Therefore, the root yaw angle q3 is fixed at zero.

    q3 = 0;

    [joint_position_world, ee_position_world] = ...
        forward_kinematics( ...
            q1, ...
            q2, ...
            q3, ...
            param.l1, ...
            param.l2);

    %% Extract positions in the local X-Z contact plane

    x_joint = ...
        joint_position_world(1);

    z_joint = ...
        joint_position_world(3);

    x_ee = ...
        ee_position_world(1);

    z_ee = ...
        ee_position_world(3);

    %% Jacobian of second joint
    %
    % The second-joint position depends only on q1.

    J_joint = [
        -param.l1 * sin(q1), 0;
         param.l1 * cos(q1), 0
    ];

    %% Jacobian of end effector

    J_ee = ...
        jacobian_2link( ...
            q1, ...
            q2, ...
            param.l1, ...
            param.l2);

    %% Cartesian velocities in the X-Z plane

    v_joint = ...
        J_joint * dq;

    v_ee = ...
        J_ee * dq;

    %% Contact at second joint

    [F_joint, joint_detail] = ...
        penalty_contact_point( ...
            z_joint, ...
            v_joint(2), ...
            param);

    %% Contact at end effector

    [F_ee, ee_detail] = ...
        penalty_contact_point( ...
            z_ee, ...
            v_ee(2), ...
            param);

    %% Contact torque

    tau_joint = ...
        J_joint.' * F_joint;

    tau_ee = ...
        J_ee.' * F_ee;

    tau_contact = ...
        tau_joint ...
        + tau_ee;

    %% Force output

    F_contact.joint = ...
        F_joint;

    F_contact.ee = ...
        F_ee;

    F_contact.total = ...
        F_joint ...
        + F_ee;

    %% Detail output

    detail.joint.position = [
        x_joint;
        z_joint
    ];

    detail.joint.velocity = ...
        v_joint;

    detail.joint.penetration = ...
        joint_detail.penetration;

    detail.joint.penetration_velocity = ...
        joint_detail.penetration_velocity;

    detail.joint.F_spring = ...
        joint_detail.F_spring;

    detail.joint.F_damper = ...
        joint_detail.F_damper;

    detail.joint.is_contact = ...
        joint_detail.is_contact;

    detail.ee.position = [
        x_ee;
        z_ee
    ];

    detail.ee.velocity = ...
        v_ee;

    detail.ee.penetration = ...
        ee_detail.penetration;

    detail.ee.penetration_velocity = ...
        ee_detail.penetration_velocity;

    detail.ee.F_spring = ...
        ee_detail.F_spring;

    detail.ee.F_damper = ...
        ee_detail.F_damper;

    detail.ee.is_contact = ...
        ee_detail.is_contact;

    detail.tau_joint = ...
        tau_joint;

    detail.tau_ee = ...
        tau_ee;

end


function [F_contact, detail] = ...
    penalty_contact_point(z_point, vz_point, param)
%PENALTY_CONTACT_POINT
% Penalty contact for one Cartesian point.

    penetration = ...
        param.z_floor ...
        - z_point;

    penetration_velocity = ...
        -vz_point;

    if penetration > 0

        F_spring = ...
            param.k_contact ...
            * penetration;

        F_damper = ...
            param.d_contact ...
            * penetration_velocity;

        Fz = ...
            F_spring ...
            + F_damper;

        % The surface pushes but never pulls.
        Fz = ...
            max(Fz, 0);

    else

        F_spring = 0;
        F_damper = 0;
        Fz = 0;

    end

    F_contact = [
        0;
        Fz
    ];

    detail.penetration = ...
        max(penetration, 0);

    detail.penetration_velocity = ...
        penetration_velocity;

    detail.F_spring = ...
        F_spring;

    detail.F_damper = ...
        F_damper;

    detail.is_contact = ...
        Fz > 0;

end